### ISSUE TITLE
Does ESP32-S2 have an FPU？

### ISSUE THREAD

**Issue by meokit** [espressif/xtensa-overlays#2]
In file xtensa-overlays/xtensa_esp32/gcc/include/xtensa-config.h
I find all XCHAR_HAVE_FP_XXX are enabled, but for esp32s2
xtensa-overlays/xtensa_esp32s2/gcc/include/xtensa-config.h
They are all disabled. Is there something wrong with the FPU with ESP32S2?
And XCHAR_HAVE_DFP_ACCEL is also enabled for esp32 but not for esp32s2, why?

**Comment by igrr** [comment]
ESP32-S2 uses a core configuration that is different from the ESP32. The following options do not exist in ESP32-S2: FPU, zero-overhead loops, MAC, DFP accelerator.

**Comment by meokit** [comment]
> ESP32-S2 uses a core configuration that is different from the ESP32. The following options do not exist in ESP32-S2: FPU, zero-overhead loops, MAC, DFP accelerator.

Thanks for your reply! I just considered ESP32-S2 an upgrade to ESP32. Now I know they are different chips.

**Comment by nopnop2002** [comment]
@igrr 


Does the ESP32-C3 have an overhead loops function?

Thank you.
